### ISSUE TITLE
F в лимитах для minValue maxValue

### ISSUE THREAD

**Issue by verhovtsev** [IlyaZh/Maiman-Workbench#10]
isTemperature задается для команды теперь, а minValue и maxValue - не команды
Соответственно их значения не пересчитываются
Мб сделать привязку по limitCode, если limitCode - температура, то и границы тоже
![c-f-2](https://user-images.githubusercontent.com/51340621/68853549-4866cf80-06eb-11ea-842f-66747232ab43.PNG)

**Comment by IlyaZh** [comment]
Да, логичная мысль. Видимо пропустил\недодумал
