### ISSUE TITLE
Диалог калибровки

### ISSUE THREAD

**Issue by verhovtsev** [IlyaZh/Maiman-Workbench#11]
Сделать диалог калибровки таким же, как диалог лимитов
![calib](https://user-images.githubusercontent.com/51340621/68853723-adbac080-06eb-11ea-8049-f14135cd5796.PNG)
![limits](https://user-images.githubusercontent.com/51340621/68853728-b0b5b100-06eb-11ea-8f54-07a8e9ded387.PNG)

**Comment by verhovtsev** [comment]
Не считывает текущее значение.
Текстом пишет неправильные границы. В ползунке границы правильные.
![000](https://user-images.githubusercontent.com/51340621/68930673-ec11b780-079f-11ea-9a82-d6808f2f8556.PNG)

**Comment by IlyaZh** [comment]
Нажимается, просто окно не убирается. Добавил, с другим багом ехе закину - проверим
