### ISSUE TITLE
Хитрый Keep checkboxes

### ISSUE THREAD

**Issue by verhovtsev** [IlyaZh/Maiman-Workbench#13]
Если драйвер уже запущен
Прога не подключена
Keep checkboxes = true
При подключении проги драйвер останавливается, потому что в него отправляются статусы

Отчасти это баг драйвера, он повторно получает статусы, которые уже установлены, и останавливается

Но может сделать более хитрую установку чекбоксов с проверкой?
Если сохраненный статус = статусу драйвера, то ничего не посылать
Устанавливать только те, которые отличаются 

Что думаешь?

**Comment by IlyaZh** [comment]
Попробую, технически могут быть косяки. Надо подумать как реализовать. Хорошо бы было, конечно, в драйвер запилить такую проверку, но уже поздно). Посмотрю, подумаю, попробую
