### ISSUE TITLE
Не работает isSigned

### ISSUE THREAD

**Issue by verhovtsev** [IlyaZh/Maiman-Workbench#8]
И в главном окне, и в диалогах
Соответственно не смог нормально проверить пределы, потому что значения кривые
![issigned](https://user-images.githubusercontent.com/51340621/68853160-5b2cd480-06ea-11ea-9ade-43ae70e87f3b.PNG)

**Comment by verhovtsev** [comment]
Не работает не только для температуры)
![iss](https://user-images.githubusercontent.com/51340621/68868402-86262100-0708-11ea-9106-20eef537dc5b.PNG)

**Comment by IlyaZh** [comment]
Поправил, потестим
