### ISSUE TITLE
Переключение C - F

### ISSUE THREAD

**Issue by verhovtsev** [IlyaZh/Maiman-Workbench#9]
При переключении температуры в главном окне не меняется юнит
Меняется только после дисконнекта/перезапуска, когда окно перерисовывается
![c-f](https://user-images.githubusercontent.com/51340621/68853240-8a434600-06ea-11ea-80f5-3f6a81bca961.PNG)

**Comment by verhovtsev** [comment]
Еще не меняется
![c-f](https://user-images.githubusercontent.com/51340621/68868334-6989e900-0708-11ea-9c70-0a0c55a77029.PNG)

**Comment by IlyaZh** [comment]
Тестируем
